### ISSUE TITLE
Cannot import module python3 + macOS 13.4

### ISSUE THREAD

**Issue by MReschenberg** [eeejay/pyax#1]
After `pip install pyax`ing, I tried to run 
```
>> import pyax
```
in a python3 env. I get the following errror:
```
Traceback (most recent call last):
  File "/Users/morganraereschenberg/pyax/examples/event_dump.py", line 25, in <module>
    import pyax
  File "/opt/homebrew/lib/python3.11/site-packages/pyax/__init__.py", line 46, in <module>
    mix_class(AXUIElementMixin)
  File "/opt/homebrew/lib/python3.11/site-packages/pyax/_mixin.py", line 79, in mix_class
    setattr(cls, "_mix_" + name, old_method)
  File "/opt/homebrew/lib/python3.11/site-packages/objc/_transform.py", line 473, in transformAttribute
    raise objc.BadPrototypeError(
objc.BadPrototypeError: '_mix:::str::' expects 5 arguments, <slot wrapper '__str__' of 'object' objects> has 0 positional arguments
```

**Comment by eeejay** [comment]
This should be fixed in 890ece921c945c03dbc99b628d4b67b98d3bfc63, sorry I only saw this now!
